SELECT
  {{ edw_scrub_str('id') }}                                     AS product_line_instance_id_nk,
  'MT-SF'                                                       AS data_src_code,
  'Product_line_instance__c'                                    AS data_src_entity_type,
  {{ edw_key_standard('product_line_instance_id_nk') }}         AS product_line_instance_pk,
  {{ edw_scrub_str('account__c') }}                             AS company_id,
  {{ edw_key_related('company_id', "'Account'") }}              AS company_fk,
  {{ edw_scrub_str('partner_id__c') }}                          AS partner_company_name,
  {{ edw_scrub_str('sales_rep__c') }}                           AS sales_rep_email,
  {{ edw_scrub_str('am_health_score__c') }}                     AS am_health_score,
  {{ edw_scrub_date('am_pli_score_last_udpated__c') }}          AS am_health_score_last_updated,
  {{ edw_scrub_str('champion_engagement_score__c') }}           AS champion_engagement_score,
  {{ edw_scrub_date('champion_score_last_udpated__c') }}        AS champion_score_last_updated,
  {{ edw_scrub_str('currencyisocode') }}                        AS currency_code,
  {{ edw_scrub_float('ah_arr_spent__c') }}                      AS assurehire_arr_spent_amt,
  {{ edw_scrub_float('cpq_arr__c') }}                           AS cpq_arr_amt,
  --  {{ edw_scrub_float('arr__c') }}                           AS arr_amt,
  {{ edw_scrub_float('arr_w_cuf__c') }}                         AS cpq_arr_with_cuf_amt,
  {{ edw_scrub_float('current_fy_cpq_arr_w_cuf__c') }}          AS curr_fy_cpq_arr_with_cuf_amt,
  {{ edw_scrub_float('subscription_arr__c') }}                  AS subscription_arr_amt,
  {{ edw_scrub_float('previous_fy_cpq_arr__c') }}               AS previous_fy_cpq_arr_amt,
  {{ edw_scrub_str('current_fy_renewal_probability__c') }}      AS curr_fy_rnwl_probability,
  {{ edw_scrub_str('current_fy_renewal_notes__c') }}            AS curr_fy_rnwl_notes,
  {{ edw_scrub_str('next_fy_renewal_probabbility__c') }}        AS next_fy_rnwl_probability,
  {{ edw_scrub_str('next_fy_renewal_notes__c') }}               AS next_fy_rnwl_notes,
  {{ edw_scrub_str('next_renewal_date__c') }}                   AS next_renewal_date,
  --  {{ edw_scrub_str('last_quality_interaction__c') }}        AS last_quality_interaction,
  --  {{ edw_scrub_str('owner__c') }}                           AS owner_name,
  {{ edw_scrub_str('practice_director__c') }}                   AS practice_director,
  {{ edw_scrub_float('number_of_use_cases__c') }}               AS number_of_use_cases,
  {{ edw_scrub_str('solution_is_working_as_expected_required__c') }}    AS solution_is_working,
  {{ edw_scrub_str('data_source__c') }}                         AS data_src,
  {{ edw_scrub_str('ein__c') }}                                 AS ein,
  TRUE                                                          AS is_active,
  {{ edw_scrub_boolean('isdeleted') }}                          AS is_deleted,
  {{ edw_scrub_boolean('pli_terminated__c') }}                  AS is_pli_terminated,
  {{ edw_scrub_date('lastactivitydate') }}                      AS last_activity_date,
  {{ edw_scrub_str('lob__c') }}                                 AS business_unit_code,
  {{ edw_scrub_str('name') }}                                   AS product_line_instance_name,
  {{ edw_scrub_str('product_line__c') }}                        AS product_line,
  {{ edw_scrub_str('sbr_notes__c') }}                           AS sbr_notes,
  {{ edw_scrub_float('tcv__c') }}                               AS total_contracted_value_amt,
  {{ edw_scrub_float('spend_vs_forecasted_percentage__c') }}    AS spend_vs_forecasted_pct,
  {{ sf_audit_fields() }}

FROM    {{ source('salesforce', 'mt_product_line_instance__c') }}
